Repository ImMorpheus/Metropolis, pull requests merged in 2020-03, with the labels that each got.

#19 Add upgrades
  src/main/java/me/morpheus/metropolis/Metropolis.java
  src/main/java/me/morpheus/metropolis/api/custom/CustomResourceLoaders.java
  src/main/java/me/morpheus/metropolis/api/event/town/UpgradeTownEvent.java
  src/main/java/me/morpheus/metropolis/api/town/Town.java
  src/main/java/me/morpheus/metropolis/api/town/Upgrade.java
  src/main/java/me/morpheus/metropolis/commands/town/TownDispatcher.java
  src/main/java/me/morpheus/metropolis/commands/town/UpgradeCommand.java
  src/main/java/me/morpheus/metropolis/commands/town/UpgradesCommand.java
  src/main/java/me/morpheus/metropolis/custom/CustomResourceLoaderRegistryModule.java
  src/main/java/me/morpheus/metropolis/event/town/MPUpgradeTownEventPost.java
  src/main/java/me/morpheus/metropolis/event/town/MPUpgradeTownEventPre.java
  src/main/java/me/morpheus/metropolis/town/MPTown.java
  src/main/java/me/morpheus/metropolis/town/upgrade/MPUpgrade.java
  src/main/java/me/morpheus/metropolis/town/upgrade/UpgradeLoader.java
  src/main/java/me/morpheus/metropolis/town/upgrade/UpgradeRegistryModule.java
Labels: Type: Enhancement

#20 Improve config files
  src/main/java/me/morpheus/metropolis/Metropolis.java
  src/main/java/me/morpheus/metropolis/api/config/EconomyCategory.java
  src/main/java/me/morpheus/metropolis/api/config/GlobalConfig.java
  src/main/java/me/morpheus/metropolis/api/config/TownCategory.java
  src/main/java/me/morpheus/metropolis/config/Global.java
  src/main/java/me/morpheus/metropolis/config/SimpleConfigService.java
  src/main/java/me/morpheus/metropolis/config/category/SimpleChatCategory.java
  src/main/java/me/morpheus/metropolis/config/category/SimpleEconomyCategory.java
  src/main/java/me/morpheus/metropolis/config/category/SimplePlotCategory.java
  src/main/java/me/morpheus/metropolis/config/category/SimpleTownCategory.java
  src/main/java/me/morpheus/metropolis/configurate/serialize/Object2IntSerializer.java
  src/main/java/me/morpheus/metropolis/listeners/SaveHandler.java
  src/main/java/me/morpheus/metropolis/rank/MPRank.java
  src/main/java/me/morpheus/metropolis/rank/RankLoader.java
  src/main/java/me/morpheus/metropolis/town/economy/TaxCollectionTask.java
  src/main/java/me/morpheus/metropolis/town/type/MPTownType.java
  src/main/java/me/morpheus/metropolis/town/type/TownTypeLoader.java
Labels: Type: Enhancement

#21 Move to Reference-based maps and narrow types where possible
  src/main/java/me/morpheus/metropolis/api/config/PlotCategory.java
  src/main/java/me/morpheus/metropolis/api/config/TownCategory.java
  src/main/java/me/morpheus/metropolis/api/data/plot/ImmutablePlotData.java
  src/main/java/me/morpheus/metropolis/api/data/plot/PlotData.java
  src/main/java/me/morpheus/metropolis/api/rank/Rank.java
  src/main/java/me/morpheus/metropolis/api/town/TownType.java
  src/main/java/me/morpheus/metropolis/api/town/Upgrade.java
  src/main/java/me/morpheus/metropolis/commands/town/plot/perm/SetCommand.java
  src/main/java/me/morpheus/metropolis/commands/town/set/NameCommand.java
  src/main/java/me/morpheus/metropolis/commands/town/set/TagCommand.java
  src/main/java/me/morpheus/metropolis/config/SimpleConfigService.java
  src/main/java/me/morpheus/metropolis/config/category/SimplePlotCategory.java
  src/main/java/me/morpheus/metropolis/config/category/SimpleTownCategory.java
  src/main/java/me/morpheus/metropolis/configurate/serialize/Reference2ByteSerializer.java
  src/main/java/me/morpheus/metropolis/configurate/serialize/Reference2ShortSerializer.java
  src/main/java/me/morpheus/metropolis/data/plot/ImmutableMPPlotData.java
  src/main/java/me/morpheus/metropolis/data/plot/MPPlotData.java
  src/main/java/me/morpheus/metropolis/rank/MPRank.java
  src/main/java/me/morpheus/metropolis/rank/RankLoader.java
  src/main/java/me/morpheus/metropolis/town/MPTown.java
  src/main/java/me/morpheus/metropolis/town/SimpleTownService.java
  src/main/java/me/morpheus/metropolis/town/listeners/InternalTownTransactionHandler.java
  src/main/java/me/morpheus/metropolis/town/type/MPTownType.java
  src/main/java/me/morpheus/metropolis/town/type/TownTypeLoader.java
  src/main/java/me/morpheus/metropolis/town/upgrade/MPUpgrade.java
  src/main/java/me/morpheus/metropolis/town/upgrade/UpgradeLoader.java
  src/main/java/me/morpheus/metropolis/util/EventUtil.java
Labels: Type: Enhancement

#22 Fix town upkeep and taxes
  src/main/java/me/morpheus/metropolis/Metropolis.java
  src/main/java/me/morpheus/metropolis/commands/admin/AdminDispatcher.java
  src/main/java/me/morpheus/metropolis/commands/admin/ForceTaxCommand.java
  src/main/java/me/morpheus/metropolis/commands/town/set/SetDispatcher.java
  src/main/java/me/morpheus/metropolis/commands/town/set/TaxCommand.java
  src/main/java/me/morpheus/metropolis/task/DailyTask.java
  src/main/java/me/morpheus/metropolis/task/InactiveCitizenTask.java
  src/main/java/me/morpheus/metropolis/task/RentTask.java
  src/main/java/me/morpheus/metropolis/task/TaxTask.java
  src/main/java/me/morpheus/metropolis/task/UpkeepTask.java
  src/main/java/me/morpheus/metropolis/task/package-info.java
  src/main/java/me/morpheus/metropolis/town/MPTown.java
  src/main/java/me/morpheus/metropolis/town/economy/AsyncTaxCollectionTask.java
  src/main/java/me/morpheus/metropolis/town/economy/TaxCollectionTask.java
  src/main/java/me/morpheus/metropolis/town/listeners/InternalTownTransactionHandler.java
  src/main/java/me/morpheus/metropolis/town/type/TownTypeLoader.java
Labels: Type: Bug, Type: Enhancement

#23 Base mob spawn handling in plots
  src/main/java/me/morpheus/metropolis/Metropolis.java
  src/main/java/me/morpheus/metropolis/api/data/plot/ImmutablePlotData.java
  src/main/java/me/morpheus/metropolis/api/data/plot/PlotData.java
  src/main/java/me/morpheus/metropolis/api/data/plot/PlotKeys.java
  src/main/java/me/morpheus/metropolis/api/event/entity/SpawnEntityTownEvent.java
  src/main/java/me/morpheus/metropolis/data/plot/ImmutableMPPlotData.java
  src/main/java/me/morpheus/metropolis/data/plot/MPPlotData.java
  src/main/java/me/morpheus/metropolis/event/entity/MPSpawnEntityTownEvent.java
  src/main/java/me/morpheus/metropolis/listeners/SpawnEntityTownHandler.java
  src/main/java/me/morpheus/metropolis/plot/SimplePlotService.java
  src/main/java/me/morpheus/metropolis/plot/listeners/InternalSpawnEntityHandler.java
Labels: Type: Enhancement

#24 Mobspawn command implementation
  src/main/java/me/morpheus/metropolis/commands/town/plot/InfoCommand.java
  src/main/java/me/morpheus/metropolis/commands/town/plot/PlotDispatcher.java
  src/main/java/me/morpheus/metropolis/commands/town/plot/set/MobSpawnCommand.java
  src/main/java/me/morpheus/metropolis/commands/town/plot/set/SetDispatcher.java
  src/main/java/me/morpheus/metropolis/commands/town/plot/set/package-info.java
Labels: Type: Enhancement

#25 Fix plot permissions
  src/main/java/me/morpheus/metropolis/commands/town/plot/perm/ListCommand.java
  src/main/java/me/morpheus/metropolis/commands/town/plot/perm/SetCommand.java
  src/main/java/me/morpheus/metropolis/data/plot/MPPlotData.java
  src/main/java/me/morpheus/metropolis/listeners/ChangeBlockTownHandler.java
  src/main/java/me/morpheus/metropolis/listeners/InteractTownHandler.java
  src/main/java/me/morpheus/metropolis/plot/listeners/InternalInteractHandler.java
  src/main/java/me/morpheus/metropolis/util/EventUtil.java
  src/main/java/me/morpheus/metropolis/util/Hacks.java
Labels: Type: Bug
